- name: installing roboshop project
  hosts: "{{component}}"
  become: yes
  roles:
  - "{{component}}"


# ansible-playbook -i inventory -e ansible_user=centos -e ansible_password=DevOps321 -e component=catalogue main.yaml
