- name: Install mongodb components
  hosts: mongodb
  become: yes
  tasks:
  - name: copy mongorepo to yum.repos.d
    ansible.builtin.copy:
      src: mongodb.repo
      src: /etc/yum.repos.d/mongo.repo

  - name: Install mongodb
    ansible.builtin.yum:
      name: mongodb-org
      state: installed    