- name: Install payment
  hosts: payment
  become: yes
  tasks:
    - name: install python 
      ansible.builtin.yum:
        name: "{{item}}"
        state: installed
      loop:
      - python36
      - gcc
      - python3-devel

    - name: check roboshop user exists or not
      ansible.builtin.command: id roboshop
      register: output     # output is a variable name.
      ignore_errors: true     

    - name: create user roboshop
      become: yes
      ansible.builtin.user:
        name: roboshop

      when: output.rc !=0        

    - name: check app directory exist or not
      ansible.builtin.stat:
        path: /app
      register: directory

    - name: print the directory status
      ansible.builtin.debug:
        msg: "output: {{directory}}"

    - name: create /app directory
      ansible.builtin.file:
        path: /app
        state: directory
      when: directory.stat.exists == False    

    - name: download payment artifact
      ansible.builtin.unarchive:
        src: https://roboshop-artifacts.s3.amazonaws.com/payment-v3.zip
        dest: /app
        remote_src: yes 
    - name: installl dependencies
      ansible.builtin.command: pip3.6 install -r requirements.txt
      args:
        chdir: /app

    - name: copy payment service
      ansible.builtin.copy:
        src: payment.service
        dest: /etc/systemd/system/payment.service      

    - name: demamon reload
      ansible.builtin.systemd:
        daemon_reload: true 

    - name: Restart payment
      ansible.builtin.service:
        name: payment
        state: restarted
        enabled: true 