- name: Install Redis components
  hosts: redis
  become: yes
  tasks:
    - name: Install Redis repo
      ansible.builtin.yum:
        name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm
        state: installed
        disable_gpg_check: true
        

    - name: Enable Redis 6.2 module
      ansible.builtin.command: dnf module enable redis:remi-6.2 -y
      remote_src: yes

    - name: Install Redis
      ansible.builtin.yum:
        name: redis
        state: installed

    - name: allow remote connection to redis
      ansible.builtin.replace: 
        path: /etc/redis.conf
        regexp: '127.0.0.1'
        replace: '0.0.0.0'

    - name: start and enable redis
      name: redis
      state: started
      enabled: yes    