# need to reffer nodejs tasks from common folder 
# catalogue is one role common is an another role need to import a task nodejs.yaml in catalogue. 

- name: install nodejs
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs

- name: setup application
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup    