- name: check roboshop user exists or not
  ansible.builtin.command: id roboshop
  register: output     # output is a variable name.
  ignore_errors: true     

- name: create user roboshop
  become: yes
  ansible.builtin.user:
    name: roboshop

  when: output.rc !=0        

- name: check app directory exist or not
  ansible.builtin.stat:
    path: /app
  register: directory

- name: print the directory status
  ansible.builtin.debug:
    msg: "output: {{directory}}"

- name: create /app directory
  ansible.builtin.file:
    path: /app
    state: directory
  when: directory.stat.exists == False

- name: download {{component}} artifact
  ansible.builtin.get_url:
    url: https://roboshop-builds.s3.amazonaws.com/{{component}}.zip
    dest: /tmp

- name: extact {{component}} artifact
  ansible.builtin.unarchive:
    src: /tmp/{{component}}.zip
    dest: /app
    remote_src: yes
