- name: copy mongo repo to yum.repos.d
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: Install mongodb shell
  ansible.builtin.yum:
    name: mongodb-org-shell
    state: installed

- name: load {{component}} data
  ansible.builtin.command: mongo --host mongodb.ljnag.space < /app/schema/{{component}}.js          
